
Parameters:
  VpcId:
    Description: Virtual Private Network to run Web Server in
    Type: AWS::EC2::VPC::Id
  PublicSubnet:
    Description: Multiple public subnets to run Web Server in
    Type: AWS::EC2::Subnet::Id
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.small
    AllowedValues:
    - t3.nano
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
    ConstraintDescription: must be a valid EC2 instance type.


Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0233214e13e500f77
      SubnetId: !Ref PublicSubnet
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref SecurityGroup
      UserData: !Base64 |
        #!/bin/bash
        yum -y install httpd
        EC2_AVAIL_ZONE=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone`
        echo "<html><body><h1>$EC2_AVAIL_ZONE</h1></body></html>" > /var/www/html/index.html
        service httpd start
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic in
      SecurityGroupIngress:
        -
          IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcId

Outputs:
  PrivateIp:
    Value: !GetAtt Instance.PrivateIp
  PublicIp:
    Value: !GetAtt Instance.PublicIp
