AWSTemplateFormatVersion: 2010-09-09

Description: S3 Bucket Demo

Parameters:
  UniqueBucketName:
    Type: String
    NoEcho: True

Resources:
  MarksBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref UniqueBucketName
      VersioningConfiguration:
        Status: Enabled
      Tags:
        -
          Key: "Name"
          Value: "DarwinsDemon"
        -
          Key: "Date"
          Value: "vandaag lullo"
        -
          Key: "Department"
          Value: "Of Magic"
        -
          Key: "Origin"
          Value: "of Species"
